# Generated by Django 2.2.1 on 2020-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200403_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagebook',
            name='status',
        ),
        migrations.AddField(
            model_name='languagebook',
            name='language',
            field=models.CharField(blank=True, choices=[('e', 'English'), ('f', 'French'), ('y', 'Yoruba')], default='e', max_length=10),
        ),
    ]
