# Generated by Django 2.2.1 on 2020-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200403_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagebook',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Yoruba', 'Yoruba')], default='English', max_length=10),
        ),
    ]
