# Generated by Django 2.2.1 on 2020-04-04 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200403_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pages', models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Yoruba', 'Yoruba')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PagesBook'),
        ),
    ]
