# Generated by Django 2.2.1 on 2020-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200404_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AlterField(
            model_name='languagebook',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Yoruba', 'Yoruba')], max_length=200),
        ),
        migrations.DeleteModel(
            name='PagesBook',
        ),
    ]
