# Generated by Django 2.2.1 on 2020-04-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200404_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklanguage', models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('Yoruba', 'Yoruba')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookLanguages'),
        ),
    ]
